services:
  postgres:
    image: postgres:16
    container_name: enactspace_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: enactspace_db
      POSTGRES_USER: enactspace_user
      POSTGRES_PASSWORD: enactspace_password
    ports:
      - "5432:5432"
    volumes:
      - enactspace_postgres_data:/var/lib/postgresql/data

volumes:
  enactspace_postgres_data: