"""Original learning activities, informed by institutional memory and primary references."""
YUNUS = 'https://www.muhammadyunus.org/post/363/seven-principles-of-social-business'
YUNUS_TYPES = 'https://www.muhammadyunus.org/post/2113/social-business'
DESIGN = 'https://dschool.stanford.edu/tools/design-thinking-bootleg'
MEMORY = 'Mémoire institutionnelle Enactus ESP, édition du 22 juillet 2026.'


def lesson(title, objective, idea, case, exercise, checklist, source=MEMORY):
    return (title, '\n\n'.join([
        'Objectif\n'+objective, 'Comprendre\n'+idea,
        'Sur le terrain\n'+case, 'À toi de jouer\n'+exercise,
        'Avant de continuer\n'+checklist, 'Pour aller plus loin\n'+source,
    ]))


COURSES = [
 ('Entrepreneuriat social : de l’idée à l’impact', 'Entrepreneuriat', 'debutant', [
  lesson('Partir du changement, pas du produit',
   'Savoir distinguer un problème social, une solution et un résultat attendu.',
   'Un problème décrit une difficulté vécue par des personnes dans un contexte précis. Une solution est une réponse possible : elle peut changer après enquête. Le résultat décrit ce qui doit devenir différent dans la vie des personnes. Commencer par une machine ou un produit peut masquer le besoin. Demande plutôt : qui rencontre quelle difficulté, à quelle fréquence et avec quelles conséquences ? Note aussi les réponses déjà utilisées et ce qu’elles coûtent en temps ou en argent.',
   'À Sinthiou Dimb, le récit de Dimbali révèle un besoin d’accès à l’eau plus pressant que la culture du dimb. Deconaane+ adapte alors la réponse. Ce cas montre pourquoi un projet doit pouvoir changer de direction après l’écoute du terrain.',
   'Choisis un problème autour de toi. Rédige trois phrases : le problème observé, une hypothèse de solution et un changement souhaité. Ajoute une question qui pourrait contredire ton hypothèse. Présente-les à un binôme.',
   'Ton problème peut-il être compris sans citer ton produit ? As-tu nommé le public et le contexte ? As-tu séparé une observation d’une supposition ?'),
  lesson('Bénéficiaire, client et partenaire',
   'Identifier qui utilise, qui paie et qui permet à la solution de fonctionner.',
   'Ces rôles ne sont pas toujours occupés par la même personne. Le bénéficiaire reçoit le changement recherché ; le client achète un produit ou un service ; un partenaire apporte une ressource, une compétence ou un accès. Dessine les flux : produit, argent, information et responsabilité. Évite de promettre un service gratuit sans savoir qui financera les coûts récurrents. Vérifie aussi qui décide réellement de l’usage et qui pourrait être exclu.',
   'Pour un atelier de transformation porté avec un GIE, les membres du groupement, les acheteurs, les artisans et les distributeurs ont des attentes différentes. Les confondre empêche de comprendre le fonctionnement réel de la chaîne.',
   'Dessine une carte de cinq acteurs autour d’une idée. Pour chacun, note ce qu’il apporte, ce qu’il reçoit et ce qu’il décide. Fais apparaître un acteur oublié : réparateur, fournisseur ou personne qui n’a pas accès au service.',
   'Chaque flux a-t-il un responsable ? Le bénéficiaire a-t-il une voix dans les décisions ? Le payeur dispose-t-il d’une raison réaliste de payer ?'),
  lesson('Organiser un premier pilote utile',
   'Transformer une idée en expérimentation courte et vérifiable.',
   'Un pilote répond à une question précise. Définis un public limité, une durée, une hypothèse à tester, une mesure et un critère d’arrêt. Prépare une solution simple et réversible. Note les ressources engagées et les difficultés. Ne généralise pas les résultats de quelques personnes à une région entière. À la fin, décide avec les participants de poursuivre, d’améliorer ou de renoncer.',
   'Les prototypes de MobiGel puis les transferts de technologies illustrent deux niveaux différents : tester un mécanisme et permettre son appropriation locale. Une démonstration qui fonctionne une fois ne prouve pas encore l’adoption durable.',
   'Écris une fiche pilote en six lignes : public, hypothèse, protocole, durée, mesure et décision attendue. Exemple pédagogique : observer pendant une semaine si trois utilisateurs arrivent à entretenir un dispositif sans l’équipe.',
   'Peux-tu expliquer ce qui ferait échouer le test ? Le consentement des participants est-il prévu ? La mesure porte-t-elle sur l’usage réel plutôt que sur les compliments ?'),
 ]),
 ('Social business avec Muhammad Yunus', 'Entrepreneuriat', 'debutant', [
  lesson('Une entreprise au service d’une cause',
   'Comprendre le modèle du social business et le distinguer d’une action ponctuelle.',
   'Chez Muhammad Yunus, le social business utilise l’activité économique pour répondre à un objectif social. Dans le modèle de type I, l’entreprise couvre ses coûts ; l’investisseur peut récupérer son apport, mais les bénéfices restent dans l’entreprise au lieu de devenir des dividendes. Yunus décrit aussi un type II : une entreprise détenue par des personnes pauvres ou défavorisées, auxquelles les bénéfices peuvent revenir. Le terme entrepreneuriat social est plus large : tout projet social ne suit pas automatiquement ces modèles.',
   'Exemple pédagogique : un service de séchage conçu pour réduire les pertes agricoles facture son usage et réserve son excédent à la maintenance et à l’accès de nouveaux utilisateurs. Cette illustration n’attribue aucun statut juridique particulier à Dimbali.',
   'Compare une distribution financée par un don, une entreprise classique et le service imaginé. Qui finance l’action suivante ? Où va l’excédent ? Qui détient les décisions ?',
   'Tu peux expliquer le mécanisme économique sans promettre une rentabilité garantie. Tu distingues mission sociale, propriété et destination du bénéfice.',YUNUS_TYPES),
  lesson('Les sept principes, dans les décisions',
   'Relier les principes de Yunus à des choix concrets.',
   'Les sept repères sont : une finalité sociale ; la viabilité économique ; le remboursement de l’apport sans dividende supplémentaire ; le réinvestissement de l’excédent après remboursement ; l’attention au genre et à l’environnement ; une rémunération au niveau du marché avec de meilleures conditions de travail ; et la joie d’entreprendre. Ils doivent se voir dans les arbitrages du quotidien, pas uniquement dans une présentation.',
   'Cas pédagogique : un atelier peut acheter un équipement plus cher mais réparable localement. Discute les effets sur les coûts, l’emploi et la durée d’utilisation. Un choix favorable à une dimension peut créer une difficulté pour une autre : il faut rendre cet arbitrage visible.',
   'Prends une idée de ton équipe. Crée une ligne par principe avec une décision possible, une preuve à chercher et une question encore ouverte. Évite de cocher automatiquement toutes les cases.',
   'Les principes apparaissent dans des décisions observables. Les limites et les hypothèses de ton exemple sont explicites.',YUNUS),
  lesson('Tester la viabilité sans oublier la mission',
   'Construire un scénario simple de coûts et vérifier son effet sur l’accès.',
   'Pour un exercice, sépare investissement initial, coûts fixes mensuels et coût variable par vente. Exemple fictif : 20 000 FCFA de coûts fixes, un prix de 1 500 FCFA et un coût variable de 1 000 FCFA donnent une marge de 500 FCFA par unité. Couvrir les coûts fixes demande alors 40 unités, avant les autres charges. Ce calcul pédagogique est une hypothèse, pas une prévision de vente. Une activité viable peut rester inaccessible au public visé : confronte le prix à sa réalité.',
   'Imagine un groupement qui exploite une solution de conservation. Le transport, la saisonnalité des produits et les pannes peuvent modifier le coût. Le bilan doit aussi suivre la réduction des pertes et la qualité de l’usage, au-delà du chiffre d’affaires.',
   'Calcule deux scénarios fictifs : ventes normales et ventes réduites de moitié. Ajoute une réserve de maintenance. Explique comment préserver l’accès si le prix couvre mal les coûts.',
   'Tes unités et hypothèses sont écrites. Tu n’as pas confondu revenus, marge et trésorerie. Le changement social conserve sa place dans ta décision.'),
 ]),
 ('Immersion : écouter avant d’agir', 'Méthode projet', 'debutant', [
  lesson('Préparer une mission avec les communautés',
   'Construire un départ dont chacun comprend le but et les limites.',
   'Une immersion est un temps d’écoute et d’apprentissage. Définis ce que l’équipe veut comprendre, puis contacte les interlocuteurs locaux pour convenir du moment et du format. Prépare les déplacements, les rôles, la langue des échanges et le matériel. N’annonce pas une technologie avant de connaître le besoin. Explique ce qui sera documenté et demande l’accord avant toute photo ou enregistrement. Une participation refusée doit rester possible sans pénalité.',
   'Le voyage des 14–18 mars 2025 relie des localités de Kaolack et de Ziguinchor. La mémoire distingue immersion, formation et transfert : ce sont des activités complémentaires, avec des objectifs différents.',
   'Rédige une fiche mission : question principale, personnes à rencontrer, programme adaptable, responsables, moyens, modalités de consentement et restitution prévue. Prépare aussi un plan si une rencontre est annulée.',
   'Les interlocuteurs ont accepté le programme. Les rôles sont répartis. Tu sais ce que l’équipe peut réellement promettre.'),
  lesson('Observer et poser des questions ouvertes',
   'Recueillir des exemples concrets sans orienter les réponses.',
   'Commence par une situation récente : « Racontez la dernière fois que cela s’est produit ». Demande ensuite ce qui a été fait, par qui, combien de temps cela a pris et ce qui a posé problème. Une question comme « Notre machine vous aiderait, non ? » cherche une approbation. Sépare dans ton carnet les paroles rapportées, ce que tu observes et ton interprétation. Croise les profils et les points de vue au lieu de consulter uniquement les personnes les plus visibles.',
   'Pour la conservation du lait, une discussion avec un producteur doit être complétée par celle d’un collecteur ou d’un acheteur. Les contraintes de conservation, de transport et d’achat peuvent diverger.',
   'Transforme cinq questions fermées en questions ouvertes. Fais un entretien de dix minutes avec un binôme. Le second binôme identifie les endroits où tu as suggéré la réponse.',
   'Chaque constat dispose d’un exemple. Les désaccords restent visibles. Tu n’as pas transformé ton interprétation en parole du participant.'),
  lesson('Restituer et décider ensemble',
   'Passer des notes de terrain à une priorité discutée.',
   'Après la mission, rassemble les observations par thème. Note les points convergents, les contradictions et les questions sans réponse. Présente une synthèse compréhensible aux interlocuteurs pour qu’ils puissent corriger les erreurs. Priorise avec eux selon l’importance du besoin, les solutions existantes, les ressources et les risques. Prévois un prochain échange : une immersion sans retour peut devenir une collecte sans relation.',
   'Le changement de priorité à Sinthiou Dimb invite à garder un diagnostic ouvert. La communauté aide l’équipe à comprendre pourquoi une réponse sur l’eau devient plus pertinente que l’idée initiale.',
   'Prépare une restitution d’une page : trois constats, deux incertitudes, une priorité proposée et une prochaine étape. Ajoute qui a participé et ce qui reste à vérifier, sans publier de coordonnées personnelles.',
   'Les interlocuteurs reconnaissent leur réalité dans la synthèse. La décision est traçable. Un rendez-vous de suivi est prévu.'),
 ]),
 ('Ciblage : choisir avec qui agir', 'Méthode projet', 'debutant', [
  lesson('Définir un public précis',
   'Décrire un groupe à partir d’un besoin plutôt que d’une catégorie vague.',
   '« Les femmes » ou « les jeunes » est trop large pour guider un pilote. Précise la localité, l’activité, les contraintes d’accès et la difficulté concernée. N’enferme pas les personnes dans une identité de bénéficiaire : elles possèdent des savoirs, des ressources et des choix. Un segment pertinent rassemble des situations proches, mais laisse apparaître les différences importantes.',
   'La mémoire de Mën Nañ distingue les contextes de Niaguiss, Saré Yoba Diéga et Sinthiou Dimb. Une même démarche de transformation ne se déploie pas identiquement auprès de ces communautés.',
   'Réécris « aider les jeunes » en une description située. Indique le besoin, les critères d’inclusion et une personne que ces critères risqueraient d’exclure.',
   'Le public est assez précis pour organiser une rencontre, sans réduire les personnes à un stéréotype.'),
  lesson('Connaître les usages et les obstacles',
   'Identifier les conditions qui permettent ou empêchent l’adoption.',
   'Un dispositif disponible n’est pas forcément utilisable. Recherche les contraintes de temps, de coût, de langue, de déplacement, d’entretien et de décision familiale ou collective. Une fiche utilisateur doit être fondée sur des observations, pas sur un personnage inventé présenté comme réel. Complète-la progressivement et conserve les éléments contradictoires.',
   'Pour un micro-jardin, l’accès à l’eau, l’espace disponible, le temps d’entretien et la possibilité de réparer le dispositif comptent autant que l’intérêt déclaré.',
   'Crée une fiche avec : tâche quotidienne, difficulté, solution actuelle, coût, obstacle et ressource disponible. Marque chaque information comme observée, rapportée ou à vérifier.',
   'Tu peux relier chaque obstacle à un exemple. Tu as rencontré des personnes qui ne souhaitent pas adopter la solution.'),
  lesson('Choisir un pilote et mesurer l’équité',
   'Expliquer pourquoi un premier groupe est choisi et qui reste hors du pilote.',
   'La facilité d’accès ne doit pas être le seul critère. Compare le besoin, la disponibilité des partenaires, la capacité de suivi et les risques d’exclusion. Un pilote limité ne prétend pas représenter toute la communauté. Annonce clairement ses critères et discute une voie d’accès future. Suis les personnes qui abandonnent : leur expérience révèle parfois un obstacle que les participants restants ne rencontrent pas.',
   'Exemple pédagogique : un atelier débute avec un petit groupement volontaire. Il faut expliquer pourquoi, documenter les coûts de participation et demander à celles qui ne viennent pas ce qui les freine.',
   'Écris trois critères de sélection, deux risques d’exclusion et une mesure corrective. Décris comment tu recueilleras un retour des personnes non participantes.',
   'Les critères sont explicables. L’échantillon et les limites figurent dans la restitution. Le droit de se retirer est respecté.'),
 ]),
 ('Brainstorming et idéation : ouvrir le champ', 'Créativité', 'debutant', [
  lesson('Poser une question qui ouvre des possibilités',
   'Transformer un diagnostic en défi de conception.',
   'Une bonne question indique un public, un contexte et un changement recherché sans imposer la solution. « Comment pourrions-nous réduire les pertes de récolte de ce groupement pendant le transport ? » ouvre plusieurs pistes. « Comment fabriquer notre séchoir ? » enferme déjà le choix. Commence par partager les faits du terrain et les limites connues, puis fais reformuler le défi par plusieurs personnes.',
   'L’évolution de SunCuiz vers les paniers thermiques rappelle que le besoin peut être servi par des réponses différentes. Une première idée n’est pas une obligation de construire le même objet jusqu’au bout.',
   'Rédige trois versions d’un défi. Demande à un binôme d’identifier la solution cachée dans chacune. Choisis la formulation qui ouvre le plus de pistes utiles.',
   'La question ne contient pas un produit imposé. Elle est reliée à un besoin que le groupe comprend.'),
  lesson('Animer une séance où chacun contribue',
   'Produire des idées variées avant de les évaluer.',
   'Proposition d’atelier : cinq minutes d’écriture individuelle, dix minutes de partage sans jugement, puis dix minutes pour combiner et développer les pistes. Une idée par note, des formulations courtes et la possibilité de dessiner. L’animateur protège la parole des plus réservés et sépare génération et sélection. Une idée étrange peut ouvrir une piste réaliste ; elle n’a pas besoin d’être acceptée telle quelle.',
   'Une équipe mêlant technique, chimie, gestion et communication peut imaginer une machine, un service, un changement d’organisation ou une formation. Cette diversité doit se retrouver dans les propositions.',
   'Avec trois personnes, produis au moins douze idées. Classe-les en familles sans les supprimer. Combine deux idées provenant de personnes différentes et décris leur nouvelle version.',
   'Tout le monde a proposé quelque chose. Les idées n’ont pas été critiquées pendant leur génération. Les pistes sont conservées avec leur contexte.'),
  lesson('Sélectionner une hypothèse à tester',
   'Choisir une piste par des critères partagés, sans confondre vote et preuve.',
   'Compare les idées selon utilité pour le public, faisabilité, coûts, risques et capacité à poursuivre sans l’équipe. Un vote repère un intérêt ; il ne démontre pas le besoin. Pour les meilleures pistes, identifie l’hypothèse la plus incertaine et le test le plus simple. Une piste moins spectaculaire peut être plus accessible ou plus facile à entretenir.',
   'Exemple pédagogique : face à des pertes alimentaires, compare un équipement, un service partagé et une meilleure organisation du transport. Les trois peuvent résoudre une partie du problème.',
   'Fais une matrice de trois idées et quatre critères. Explique la note la plus fragile. Propose un test qui permettrait de changer de choix.',
   'Le groupe peut expliquer sa décision. Une hypothèse risquée et un protocole de test sont écrits.'),
 ]),
 ('Design thinking : du terrain au prototype', 'Créativité', 'intermediaire', [
  lesson('Cinq modes, des allers-retours',
   'Utiliser une démarche de conception centrée sur les personnes.',
   'La d.school de Stanford propose cinq modes : empathie, définition, idéation, prototype et test. Ce sont des outils reliés plutôt qu’une suite rigide : un test peut renvoyer à l’écoute ou à la définition du problème. L’empathie demande de comprendre les expériences ; la définition formule un point de vue utile ; l’idéation ouvre les options ; le prototype rend une hypothèse observable ; le test permet d’apprendre.',
   'Exercice de lecture de Deconaane+ : distingue le besoin observé à Sinthiou Dimb, la priorité choisie, la réponse technique et les questions de suivi. L’objectif n’est pas d’affirmer que l’équipe utilisait ce vocabulaire, mais d’apprendre avec son histoire.',
   'Dessine les cinq modes autour d’un cas. Ajoute deux flèches de retour et explique quel résultat pourrait obliger à revenir en arrière.',
   'Tu sais pourquoi un test peut modifier le diagnostic. Tu évites de présenter le processus comme une garantie de réussite.',DESIGN),
  lesson('Un prototype pour une question',
   'Choisir un objet ou un scénario adapté à l’incertitude.',
   'Ne cherche pas à fabriquer toute la solution immédiatement. Pour tester une compréhension, utilise un dessin ou une maquette. Pour un parcours de service, joue une scène. Pour une fonction technique, isole le mécanisme. Écris la question à laquelle le prototype doit répondre, ce qu’il représente et ce qu’il ne représente pas. Un prototype destiné à un public doit rester compréhensible et ne pas faire croire qu’il s’agit d’un produit final.',
   'Pour un jardin sur table, une maquette peut aider à discuter la hauteur et l’espace ; une installation séparée peut ensuite tester l’arrosage. Le même prototype n’est pas obligé de répondre aux deux questions.',
   'En vingt minutes, construis une représentation simple de ton idée. Prépare trois consignes neutres pour observer son usage, puis demande à quelqu’un de l’essayer sans le guider vers le résultat attendu.',
   'Le test vise une question précise. Les limites du prototype sont annoncées. L’observation distingue aide de l’équipe et autonomie de l’utilisateur.'),
  lesson('Apprendre des retours, puis itérer',
   'Décider d’une amélioration fondée sur l’usage.',
   'Consigne ce que la personne a réussi, ce qui l’a bloquée, ce qu’elle a dit et ce que tu interprètes. Une difficulté d’utilisation ne signifie pas forcément un manque de formation : elle peut révéler un défaut de conception. Regroupe les retours et propose un changement limité que tu pourras retester. Conserve une trace des versions pour ne pas oublier pourquoi une solution a évolué.',
   'Exemple pédagogique : un utilisateur n’arrive pas à nettoyer un réservoir sans démonter l’ensemble. L’équipe peut tester une ouverture différente avant de conclure qu’une notice supplémentaire suffit.',
   'Rédige une fiche d’itération : observation, hypothèse explicative, changement, nouveau test et critère de réussite. Fais relire la distinction entre observation et interprétation.',
   'La prochaine version répond à un retour précis. Tu sais comment vérifier son amélioration. Les résultats négatifs restent dans le carnet de projet.'),
 ]),
 ('Vivre et transmettre Enactus ESP', 'Mémoire du club', 'debutant', [
  lesson('2015–2026 : une histoire à poursuivre',
   'Relier les générations aux décisions et aux projets du club.',
   'En 2015, M. Mare présente le mouvement aux étudiants de l’ESP et le club démarre avec trois membres. Javelisel et Soukhali Gokh lancent les premières actions. La qualification de 2017 conduit à une préparation pour Londres, mais les visas sont refusés. En 2018, Dimbali et Deconaane accompagnent la première participation effective aux États-Unis. La grève de 2019 puis la pandémie poussent l’équipe à s’adapter. SHERY apparaît en 2021 ; le retour mondial de 2022 précède une nouvelle génération avec Terrasen et Aquatus.',
   'En 2025–2026, la mémoire évoque une réorganisation, des formations avec les alumni et deux transferts de technologies à Mbour. Une histoire de club comprend aussi les pauses et les reprises : elles enseignent comment transmettre.',
   'Choisis trois moments dans les Archives. Pour chacun, écris le défi rencontré, le choix de l’équipe et ce qu’une nouvelle recrue peut en apprendre.',
   'Tu distingues qualification et participation. Tu n’as pas transformé un objectif en réalisation.'),
  lesson('La Minute de l’enacteur : une voix, un message',
   'Préparer une intervention courte qui apporte quelque chose à l’équipe.',
   'Avant la fin d’une réunion, un enacteur ou une enactrice reçoit la parole pour partager une réflexion, un conseil ou une expérience. Ce moment ne demande pas un bilan de tâches. Le PV du 12 décembre 2024 rappelle son intention : faire passer un message de vie. Une minute réussie peut contenir une scène vécue, une idée claire et une invitation simple. Tu peux être drôle, calme ou touchant : l’objectif est de parler avec sincérité et de laisser une idée qui reste.',
   'Aïta Ndir DIA invite en 2020 à profiter du temps pour apprendre. Ibrahima CISSE questionne la comparaison aux autres. Les PV de 2025 parlent aussi de courage, d’entraide et de liens créés pendant les voyages.',
   'Prépare un texte d’environ une minute : une accroche, une idée, un exemple et une invitation. Chronomètre-toi puis demande à un binôme ce qu’il retient. Explore les Minutes dans les Archives pour écouter d’autres voix.',
   'Ton message peut être résumé en une phrase. Tu ne révèles pas une confidence d’autrui. L’équipe reçoit une invitation concrète.'),
  lesson('Mentors et passation : faire vivre l’héritage',
   'Reconnaître les personnes qui accompagnent et organiser une transmission utile.',
   'Le professeur Ndiaga NDIAYE a été Faculty Advisor d’Enactus ESP. Il a accompagné les étudiants, leur structuration et leurs projets. L’hommage partagé par le club garde la mémoire d’un mentor généreux, motivant et présent auprès des générations. Honorer cet héritage signifie aussi rendre le travail reprenable : documenter les décisions, expliquer les essais et accueillir les nouvelles recrues.',
   'Une passation transmet davantage qu’un dossier de résultats : elle décrit les contacts autorisés, les responsabilités, les dépenses, les versions techniques et ce qui reste à vérifier. Les personnes qui arrivent doivent pouvoir poser des questions.',
   'Construis une fiche de passation d’une page pour une tâche réelle. Ajoute une décision expliquée, une difficulté, une ressource et la prochaine action. Relis l’hommage au professeur dans le Hall of Fame.',
   'La fiche permet à quelqu’un d’agir sans toi. Les responsabilités sont visibles. Les informations personnelles restent dans les espaces autorisés.'),
 ]),
]

# Questions originales. Le bon choix n’est pas systématiquement placé en premier.
QUIZ_ITEMS = {
 'Entrepreneuriat social : de l’idée à l’impact': [
  ('Que décrit un résultat social ?', ['Le nombre de réunions', 'Un changement dans la vie des personnes', 'Le nom du prototype'], 1),
  ('Le bénéficiaire et le payeur…', ['Sont toujours identiques', 'Doivent être exclus du diagnostic', 'Peuvent être différents'], 2),
  ('Un pilote sert d’abord à…', ['Tester une hypothèse précise', 'Annoncer un déploiement national', 'Garantir le succès'], 0)],
 'Social business avec Muhammad Yunus': [
  ('Dans le type I après remboursement de l’apport, l’excédent…', ['Devient un dividende personnel', 'Reste dans l’entreprise', 'Est interdit'], 1),
  ('Dans l’exemple, 20 000 / 500 correspond à…', ['40 unités pour couvrir les coûts fixes considérés', 'Un revenu garanti', '40 FCFA de profit'], 0),
  ('Le type II décrit notamment…', ['Une activité toujours sans propriétaire', 'Une simple présentation', 'Une entreprise détenue par des personnes pauvres ou défavorisées'], 2)],
 'Immersion : écouter avant d’agir': [
  ('Quelle question est la plus ouverte ?', ['Vous aimez notre machine ?', 'Vous voulez dire oui ?', 'Racontez la dernière fois que cela est arrivé'], 2),
  ('Avant une photo, il faut…', ['Demander l’accord', 'Supposer le consentement', 'Publier puis prévenir'], 0),
  ('Une restitution utile…', ['Cache les contradictions', 'Permet aux interlocuteurs de corriger la synthèse', 'Annonce uniquement le produit'], 1)],
 'Ciblage : choisir avec qui agir': [
  ('Un public utile au pilote est…', ['Tout le monde', 'Un groupe situé et défini par un besoin', 'Le plus grand groupe possible'], 1),
  ('Un obstacle à l’adoption peut être…', ['Le titre du pitch uniquement', 'Le nombre de logos', 'Le coût ou la maintenance'], 2),
  ('Les personnes qui quittent un pilote…', ['Peuvent révéler un obstacle important', 'Ne comptent jamais', 'Prouvent forcément un manque de motivation'], 0)],
 'Brainstorming et idéation : ouvrir le champ': [
  ('Pendant la génération d’idées, on…', ['Critique immédiatement', 'Sépare génération et sélection', 'Écoute une seule personne'], 1),
  ('Un vote prouve-t-il le besoin ?', ['Toujours', 'Seulement avec un joli prototype', 'Non, il indique un intérêt du groupe'], 2),
  ('Après sélection, il faut…', ['Tester une hypothèse risquée', 'Écarter le terrain', 'Tout construire immédiatement'], 0)],
 'Design thinking : du terrain au prototype': [
  ('Les cinq modes sont…', ['Une suite impossible à modifier', 'Des outils entre lesquels on peut revenir', 'Un classement de projets'], 1),
  ('Un prototype doit surtout…', ['Ressembler à un produit fini', 'Coûter cher', 'Répondre à une question précise'], 2),
  ('Une itération utile part…', ['D’une observation de l’usage', 'D’un slogan', 'Du seul avis de l’équipe'], 0)],
 'Vivre et transmettre Enactus ESP': [
  ('La première participation effective à la World Cup a lieu en…', ['2017', '2018', '2015'], 1),
  ('La Minute est d’abord…', ['Un bilan obligatoire des tâches', 'Une sélection de candidat', 'Un message, une réflexion ou un conseil à l’équipe'], 2),
  ('Le professeur Ndiaga NDIAYE a accompagné le club comme…', ['Faculty Advisor', 'Un projet', 'Un sponsor fictif'], 0)],
}

COURSES.append(('Études de terrain : Terrasen et SHERY', 'Mémoire du club', 'intermediaire', [
 lesson('Terrasen : une rencontre devient un diagnostic',
  'Reconstituer le passage d’une rencontre à un choix de terrain.',
  'La mémoire situe la naissance de Terrasen en 2022, après une rencontre au Salon du Polytechnicien avec Keba, résident de Ndiédieng. L’invitation à Haffé et Ndiobène Tallène conduit l’équipe à examiner la dépendance à l’agriculture pluviale et les contraintes de revenus. Une opportunité de rencontre ouvre le terrain ; elle ne remplace pas l’enquête. Le micro-jardinage sur table et la transformation des récoltes relient alors production, conservation et valeur économique.',
  'Le dossier décrit des tables réalisées avec des matériaux simples, puis le goutte-à-goutte et un prototype d’arrosage avec carte ESP32, capteur d’humidité, relais et pompe. Ces dispositifs appellent aussi des questions d’entretien, de disponibilité de l’eau et de fabrication locale. Une hausse de rendement annoncée comme anticipée à Haffé reste une perspective, pas un résultat déjà acquis.',
  'Dessine la chaîne du projet : besoin, production, irrigation, transformation, vente et entretien. Place une question de terrain à chaque étape. Indique qui pourrait y répondre.',
  'Ta carte distingue technologie et changement recherché. Tu sais expliquer pourquoi une prévision ne doit pas être présentée comme un résultat.'),
 lesson('SHERY : concevoir avec les usages et les contraintes',
  'Lire une innovation sociale comme un ensemble de choix d’accès et d’usage.',
  'SHERY apparaît en 2021 autour de la précarité menstruelle. Le projet associe protections réutilisables et sensibilisation. La mémoire décrit une protection avec quatre couches et un système d’attache par boutons pression. Le problème ne se résume pourtant pas à fabriquer un objet : coût, accès à l’information, conditions de lavage, espace et préférences des utilisatrices influencent l’usage. Un entretien doit laisser la possibilité de ne pas répondre à une question intime.',
  'Le premier prix du Salon du Polytechnicien 2023 marque le parcours du projet. Il ne remplace pas un suivi des usages. Les perspectives techniques et les objectifs commerciaux décrivent ce que l’équipe souhaite explorer ; ils doivent rester distingués des réalisations documentées. Ce cours ne donne pas de conseil médical ni de garantie sur un produit.',
  'Prépare une grille de conception avec cinq critères d’usage. Pour chacun, propose une question respectueuse et une observation possible sans collecter d’information intime inutile.',
  'Les utilisatrices peuvent choisir et exprimer un désaccord. Tes conclusions ne dépassent pas les informations effectivement recueillies.'),
 lesson('Transférer une technologie, transmettre une capacité',
  'Définir ce qui permet de continuer une activité après le départ de l’équipe.',
  'La méthode du club relie ciblage, immersion, brainstorming, design thinking, transfert de technologie et recueil d’impact. Un transfert est une appropriation : comprendre le procédé, l’utiliser, l’entretenir et savoir à qui demander de l’aide. Décompose l’apprentissage, fais pratiquer les personnes et observe les gestes. Documente les pièces, les coûts, les fournisseurs et les adaptations locales. Une photographie de remise de matériel ne suffit pas à montrer cette capacité.',
  'Les missions de mars 2025 et les PV abordent transformations alimentaires, séchoirs, gestion et suivi. La mémoire rappelle aussi les transferts réalisés à Mbour pendant la restructuration 2025–2026. Une continuité de terrain peut coexister avec une réorganisation interne : le récit doit conserver ces deux dimensions.',
  'Construis une fiche de transfert : compétence, démonstration, essai autonome, entretien, responsable local et date de suivi. Prévois un retour lorsque le dispositif ne fonctionne pas comme prévu.',
  'La réussite se voit dans une pratique autonome. Le prochain suivi a un responsable et une date ; les difficultés ont une place dans le compte rendu.'),
]))
QUIZ_ITEMS['Études de terrain : Terrasen et SHERY'] = [
 ('Dans le récit de Terrasen, une rencontre sert à…', ['Prouver tous les résultats', 'Ouvrir un terrain à comprendre', 'Éviter les échanges locaux'], 1),
 ('Le prix de SHERY en 2023…', ['Garantit tous les usages', 'Remplace la mesure d’impact', 'Marque une étape de son parcours'], 2),
 ('Un transfert réussi permet notamment…', ['Une pratique autonome et un suivi', 'Une seule photo de remise', 'Le départ sans contact local'], 0),
]
