"""Additional explanations and worked reasoning for the practice curriculum."""
EXPLANATIONS = {
"Partir du changement, pas du produit": """Une finalité sociale décrit une amélioration dans une situation vécue : gagner du temps, accéder à un service ou mieux vivre d’une activité. La solution est le moyen choisi pour obtenir ce changement. Commence par écrire la finalité sans nommer un objet. Tu pourras alors comparer une technologie, une formation et une organisation différente.

Imagine un groupe qui perd une récolte avant la vente. Un séchoir peut être une piste, mais un transport mieux organisé ou un calendrier de collecte peuvent aussi répondre à une partie du besoin. Demande où se produit la perte et qui peut agir à cet endroit. Le projet devient entrepreneurial lorsqu’il organise des ressources et une activité capable de continuer.

Pour relire ton exercice, vérifie que le public, la difficulté et le changement apparaissent. « Construire un séchoir innovant » décrit un moyen. « Réduire les pertes entre récolte et vente pour ce groupement » décrit une direction sociale. La prochaine étape consiste à vérifier quelle réponse est utile et accessible dans ce contexte.""",
"Bénéficiaire, client et partenaire": """Pour rendre les rôles visibles, dessine les échanges : qui reçoit le produit, qui reçoit le changement, qui fournit une ressource et qui paie ? Une même personne peut avoir plusieurs rôles. Un groupement peut utiliser un équipement, financer son entretien et bénéficier d’une activité plus régulière.

Une offre doit expliquer ce que chaque acteur obtient. Un partenaire peut faciliter l’accès au matériel, mais le fonctionnement quotidien doit rester financé. Le coût de transport, l’entretien et le temps de travail existent même lorsqu’une personne ne paie pas directement un service. Prépare donc un scénario de continuité après le soutien initial.

Dans ton exercice, une carte correcte relie les acteurs par des flux précis. Si tu relies tout au seul mot « aide », précise la nature de l’échange. Demande également qui décide : celui qui finance ne doit pas faire disparaître les contraintes des personnes qui utilisent. Les rôles et les règles de décision permettent de concevoir une offre socialement utile et opérationnelle.""",
"Organiser un premier pilote utile": """Un pilote permet de réduire une incertitude avant d’engager davantage de ressources. Il faut choisir une question suffisamment limitée pour que les observations aient un sens. Tu peux tester l’autonomie sur un geste, l’accessibilité d’un horaire ou une demande pour un produit. Ne cherche pas à démontrer tout le projet dans un seul essai.

Prépare un relevé avec date, condition d’essai, observation et difficulté. Définis le critère avant de commencer pour éviter de réinterpréter après coup tout résultat comme une réussite. Prévois aussi les situations dans lesquelles l’essai doit être interrompu ou adapté.

Après ton exercice, distingue ce que le pilote apprend et ce qu’il ne permet pas de conclure. Si trois personnes parviennent à utiliser un dispositif, tu as une observation sur ces usages. Tu ne connais pas encore les besoins de toute la localité ni la continuité sur plusieurs mois. L’étape suivante doit répondre à une question encore ouverte et être décidée avec les participants.""",
"Une entreprise au service d’une cause": """Le social business, dans l’approche de Muhammad Yunus, donne une finalité sociale à une entreprise qui organise une offre et cherche à couvrir ses coûts. Pour le type I, les investisseurs peuvent récupérer leur apport, puis les excédents restent dans l’entreprise. Le type II concerne notamment une entreprise détenue par des personnes pauvres ou défavorisées, qui bénéficient de son activité. Il faut annoncer le modèle dont on parle.

Une entreprise sociale au sens large ne suit pas nécessairement exactement ces règles. L’enjeu de la leçon est de comprendre une approche précise, puis de voir ce qu’elle implique pour les prix, le financement et les décisions. Le projet doit conserver une mission claire même lorsqu’il rencontre une demande commerciale intéressante.

Pour ton exercice, choisis une cause, une offre et un mode de financement. Demande ce que deviendra un excédent et comment seront prises les décisions. Une présentation cohérente explique à la fois le changement recherché et l’organisation économique. Elle ne réduit pas le social business à une activité gratuite ou à une entreprise simplement généreuse.""",
"Les sept principes, dans les décisions": """Les principes peuvent être lus comme des questions de gestion : quelle cause sert l’entreprise, comment couvre-t-elle ses coûts, que deviennent l’apport initial et les excédents, comment respecte-t-elle l’environnement et le travail des personnes ? La joie dans l’action rappelle aussi que l’engagement peut être exigeant tout en restant porteur de sens.

Imagine une activité qui propose un produit accessible. Réduire le prix aide l’accès, mais si les recettes ne permettent plus de remplacer les pièces ou de payer correctement le travail, la continuité se fragilise. La décision doit donc chercher une organisation qui respecte ensemble mission, fonctionnement et conditions de travail.

Pour relire ton exercice, transforme chaque principe en une décision observable. « Nous respectons l’environnement » doit conduire à examiner des matériaux, des consommations ou des déchets. « Les excédents sont réinvestis » doit être relié à une règle et à un suivi. Un principe devient utile lorsqu’il change effectivement une manière de gérer l’activité.""",
"Tester la viabilité sans oublier la mission": """La viabilité économique commence par un calcul explicite. Dans l’exemple fictif du cours, une marge unitaire de 500 FCFA contribue à couvrir 20 000 FCFA de coûts fixes ; quarante unités couvrent ces seuls coûts considérés. Il faut encore examiner les investissements, les dates d’encaissement et la demande. Un résultat de calcul ne crée pas les clients.

Teste aussi l’accès au produit. Une hausse du prix peut améliorer la marge et exclure les personnes que le projet souhaite servir. Un financement complémentaire, une organisation différente ou une réduction de coût peuvent être étudiés, sans supposer qu’une subvention sera toujours disponible.

Après l’exercice, présente au moins deux scénarios de volume et explique les hypothèses. Ajoute une contrainte sociale : coût pour l’utilisateur, temps nécessaire ou accès au service. Une décision de social business doit rester compréhensible sur les deux plans. Si elle résout le budget en abandonnant le public visé, la mission doit être réexaminée avec l’offre.""",
"Préparer une mission avec les communautés": """Une mission commence avant le départ. Clarifie l’objectif avec les interlocuteurs : une première rencontre, un diagnostic, une formation et un suivi ne demandent pas la même préparation. Explique la durée disponible et les limites de l’équipe. Les personnes doivent savoir ce qui sera discuté et ce qui n’est pas promis.

Prépare les rôles : qui mène l’échange, qui prend des notes, qui observe et qui organise la restitution ? Anticipe les horaires, les langues utilisées et les conditions d’accès. Une préparation trop centrée sur le transport peut oublier les informations nécessaires au diagnostic.

Pour ton exercice, écris une question principale de mission et trois informations indispensables. Prévois un moment pour remercier, reformuler ce qui a été appris et annoncer la prochaine étape. Si le groupe ne peut pas revenir rapidement, cette limite doit être expliquée. Une immersion construit une relation ; elle ne se limite pas à recueillir des réponses puis repartir.""",
"Observer et poser des questions ouvertes": """Une observation décrit un geste ou une situation : une personne attend un outil, change de récipient ou interrompt une opération. L’interprétation propose une explication. Garde les deux séparées pour pouvoir demander : « Qu’est-ce qui vous a conduit à faire cela ? » Une réponse peut révéler une contrainte que l’équipe n’avait pas imaginée.

Les questions sur un événement récent donnent souvent plus de détails que les opinions générales. Demande le déroulement, puis explore le temps, le coût et les difficultés. Si tu présentes trop tôt ton produit, l’échange risque de devenir une discussion pour te faire plaisir plutôt qu’un récit des pratiques.

Après l’exercice, repère une question orientée et transforme-la. « Vous aimeriez gagner du temps avec notre appareil ? » devient « Quelle étape vous prend le plus de temps aujourd’hui ? » La nouvelle formulation laisse apparaître d’autres réponses. Ton objectif est de comprendre une expérience et de laisser le terrain modifier ta proposition.""",
"Restituer et décider ensemble": """Une restitution transforme les notes en une compréhension partageable. Organise les informations par thèmes et conserve les divergences. Explique ce qui revient dans plusieurs échanges et ce qui concerne seulement une personne. Les interlocuteurs doivent pouvoir corriger une phrase ou signaler une contrainte oubliée.

La décision vient après cette clarification. Compare les pistes selon le besoin, les moyens, les risques et la continuité. Un choix peut rester provisoire : on peut décider d’un test plutôt que d’un équipement final. Indique qui participe à la décision et qui portera la prochaine étape.

Pour ton exercice, termine la synthèse par une question : « Voici ce que nous avons compris ; qu’avons-nous oublié ? » Prépare ensuite une action, un responsable et une date. Si tu ne peux pas expliquer pourquoi cette action a été retenue, reprends les échanges. Une restitution utile relie l’écoute au travail qui suit et garde la possibilité de revoir le choix.""",
"Définir un public précis": """Un public se définit par une situation utile au projet : activité, lieu, difficulté et conditions d’accès. Les catégories générales peuvent masquer des expériences différentes. Deux personnes qui produisent le même aliment peuvent avoir des volumes, des équipements ou des débouchés très différents.

Commence par une hypothèse de public, puis confronte-la aux rencontres. Demande qui rencontre le besoin le plus pressant, qui dispose de ressources et qui est difficile à atteindre. Le premier groupe du pilote peut être limité pour organiser un suivi, mais cette limite doit être expliquée.

Après l’exercice, vérifie que ta description permet de décider qui rencontrer. « Les jeunes » reste trop large. « Des jeunes d’une localité qui cherchent une première activité de transformation et n’ont pas accès à un équipement » donne un point de départ, à vérifier. Le ciblage devient utile lorsqu’il guide le diagnostic et laisse apparaître les personnes que le projet pourrait exclure.""",
"Connaître les usages et les obstacles": """L’adoption ne dépend pas uniquement de l’intérêt pour une idée. Une personne doit pouvoir l’intégrer à son activité : disposer du temps, du lieu, des moyens et des compétences nécessaires. Un coût de déplacement ou un horaire peut empêcher l’usage même lorsque le produit plaît.

Compare la proposition avec la solution actuelle. Celle-ci peut sembler moins performante et rester préférable parce qu’elle est connue, disponible ou facile à réparer. Comprendre cette préférence aide à concevoir une réponse accessible plutôt qu’à conclure que les personnes résistent au changement.

Pour ton exercice, décris le parcours d’une personne fictive avant, pendant et après l’utilisation. À chaque étape, ajoute un obstacle et une ressource possible. Demande ensuite quel obstacle exige une modification du produit, de l’organisation ou du financement. Ton analyse doit relier une difficulté à une situation concrète ; une simple liste de mots ne suffit pas à choisir une amélioration.""",
"Choisir un pilote et mesurer l’équité": """Un groupe facilement disponible n’est pas automatiquement le groupe le plus pertinent. Compare le besoin, les conditions de suivi et les contraintes de participation. Des critères annoncés rendent le choix compréhensible et permettent de discuter les personnes qui restent hors du pilote.

L’équité demande de regarder les obstacles, pas seulement de proposer la même chose à tous. Une séance identique peut être moins accessible à une personne qui doit se déplacer loin ou s’occuper d’un enfant. Une adaptation d’horaire, un support ou une autre modalité peuvent améliorer l’accès.

Après l’exercice, relis tes critères du point de vue d’une personne non retenue. Peut-elle comprendre le choix et connaître une prochaine possibilité de participation ? Prévois aussi un retour des personnes qui abandonnent. Leur expérience peut révéler une difficulté cachée par les résultats de ceux qui restent. Le pilote doit apprendre sur l’usage et sur l’accès, sans prétendre représenter tout le public.""",
}
EXPLANATIONS.update({
"Poser une question qui ouvre des possibilités": """Un défi de conception relie un public, une situation et un changement recherché. Il doit être assez précis pour guider la réflexion et assez ouvert pour laisser plusieurs réponses. Une phrase trop large, comme « améliorer la vie », rend les idées difficiles à comparer. Une phrase qui contient déjà une machine empêche d’explorer d’autres approches.

Commence par partager un constat du terrain, puis demande comment le rendre moins contraignant. Des réponses peuvent porter sur un objet, un service, une information ou une organisation. Cette diversité aide à éviter de choisir la première proposition seulement parce qu’elle est familière à l’équipe.

Pour relire ton exercice, souligne les mots qui imposent une solution. Remplace « comment installer notre équipement ? » par une question sur le besoin et l’usage. Fais reformuler le défi par un binôme : s’il peut proposer des réponses différentes, la formulation ouvre des possibilités. Chaque idée doit ensuite revenir au problème, pas seulement à l’envie de fabriquer quelque chose.""",
"Animer une séance où chacun contribue": """Une séance d’idéation sépare la production d’idées et leur évaluation. L’écriture individuelle au début évite que la première personne qui parle donne toute la direction. Le partage permet ensuite de combiner les propositions et de découvrir des compétences différentes. L’animateur rappelle le défi et protège un temps où l’on ne critique pas immédiatement.

Une idée peut être décrite par une phrase ou un dessin. Demande comment elle fonctionnerait et quel besoin elle servirait. Le groupe peut reprendre une proposition pour l’améliorer ; l’objectif n’est pas de défendre la propriété de chaque note. Les idées inhabituelles peuvent suggérer une organisation réaliste après adaptation.

Après l’exercice, regarde qui a contribué et quelles familles de réponses apparaissent. Si toutes les pistes sont des machines, invite le groupe à imaginer aussi un service ou une autre répartition du travail. La qualité de la séance se voit dans la diversité utile des propositions, puis dans la capacité à les sélectionner selon des critères partagés.""",
"Sélectionner une hypothèse à tester": """La sélection commence par des critères connus du groupe. Compare l’utilité, l’accès, les coûts, la faisabilité et la continuité. Un vote peut repérer une préférence, mais il ne démontre ni le besoin ni le fonctionnement. Une note doit être expliquée pour que le groupe distingue connaissance et intuition.

Pour chaque idée retenue, identifie ce qui pourrait l’empêcher de réussir. Si l’équipe ignore si les utilisateurs accepteront un équipement partagé, un test d’organisation peut être plus urgent qu’un montage technique. Si le mécanisme est incertain, un essai limité peut répondre à cette question avant de fabriquer l’ensemble.

Dans ton exercice, repère la note la moins étayée de la matrice. Prépare une observation qui pourrait la modifier. La décision devient plus solide lorsque le groupe sait ce qui le ferait changer d’avis. Sélectionner n’est pas fermer définitivement le raisonnement : c’est choisir la prochaine question d’apprentissage et les moyens raisonnables pour y répondre.""",
"Cinq modes, des allers-retours": """Les modes du design thinking aident à organiser l’apprentissage autour des personnes. L’empathie recueille leurs expériences ; la définition précise le problème ; l’idéation ouvre les options ; le prototype représente une réponse ; le test observe son usage. Le schéma n’impose pas un parcours identique à chaque équipe.

Imagine un test où une personne ne peut pas entretenir l’objet. L’équipe peut revenir au prototype pour changer une ouverture, mais aussi à l’écoute pour comprendre les conditions de nettoyage. Un retour en arrière peut donc éviter d’améliorer un détail d’une réponse qui reste mal adaptée.

Pour relire ton exercice, explique deux flèches de retour par des événements concrets. « Revenir à l’empathie parce que les horaires d’usage ont été mal compris » montre un apprentissage. Une flèche sans raison ne dit pas encore comment le processus aide le projet. La méthode donne des outils pour avancer avec les observations ; elle ne garantit pas automatiquement une solution réussie.""",
"Un prototype pour une question": """Le prototype doit représenter ce qui est nécessaire à l’observation. Un dessin peut tester la compréhension, une maquette peut aider à discuter l’encombrement et une mise en scène peut tester un parcours de service. Ces représentations permettent d’apprendre avant d’investir dans une réalisation complète.

Écris la consigne du test sans guider vers la réponse souhaitée. Observe les hésitations, les demandes d’aide et les gestes. Une réussite obtenue après plusieurs explications ne doit pas être présentée comme un usage autonome. Les limites du prototype doivent être annoncées, notamment s’il ne représente pas une performance technique réelle.

Après ton exercice, formule une conclusion et une question restante. Si une maquette confirme que la hauteur convient, elle n’a pas encore vérifié l’irrigation ou la résistance. Un bon prototype réduit une incertitude et aide à choisir le suivant. La finition peut être simple ; la question et l’observation doivent être précises.""",
"Apprendre des retours, puis itérer": """Une itération est une nouvelle version liée à un apprentissage. Commence par relire les observations sans attribuer trop vite la difficulté à l’utilisateur. Un geste impossible ou une consigne incomprise peut révéler une conception peu adaptée. Le retour doit conduire à une hypothèse explicative, puis à un changement vérifiable.

Garde une fiche avec version, constat, modification et nouveau test. Essaie de limiter les changements simultanés pour comprendre ce qui produit l’amélioration. Le retour des personnes qui n’adoptent pas la solution est aussi utile que celui des utilisateurs satisfaits.

Dans ton exercice, distingue « la personne n’a pas ouvert le réservoir » et « l’ouverture est difficile à repérer ». La première phrase décrit ; la seconde propose une explication. Tu peux tester une indication ou une forme différente pour vérifier cette hypothèse. La nouvelle version doit répondre à un problème concret, pas seulement donner une impression de nouveauté.""",
"2015–2026 : une histoire à poursuivre": """Une histoire de club relie les générations par des choix et des connaissances. Les projets changent, tandis que certaines questions reviennent : comment rencontrer les personnes, financer un essai, former à une technologie et suivre son usage ? Lire plusieurs périodes permet de voir cette continuité sans effacer les différences de contexte.

Les interruptions de calendrier et les réorganisations font partie du parcours. Elles demandent de conserver les documents, de clarifier les responsabilités et de maintenir les relations. La génération suivante reçoit des ressources, mais aussi des questions auxquelles elle doit répondre avec son propre terrain.

Pour ton exercice, associe chaque moment choisi à un enseignement utilisable aujourd’hui. Une qualification apprend à organiser une préparation ; une adaptation de projet apprend à réexaminer un besoin ; une passation apprend à expliquer des décisions. Ton récit devient vivant lorsque les dates éclairent l’action. Tu ne rejoins pas seulement un bilan : tu rejoins un collectif dont tu peux continuer l’apprentissage.""",
"La Minute de l’enacteur : une voix, un message": """La Minute offre un espace personnel au sein d’une réunion collective. Une scène vécue ou une question peut ouvrir le propos ; une idée claire lui donne sa direction ; une invitation permet à chacun de prolonger la réflexion. Il n’est pas nécessaire d’imiter le ton d’une autre personne. La sincérité et la clarté comptent davantage qu’une formule spectaculaire.

Les interventions de Seydina TOURE, Ibrahima CISSE, Betty KANE, Mouhamadou Moustapha MBAYE et Papa Idrissa WADE appartiennent à l’année 2020. Elles abordent charisme, comparaison, maîtrise de soi, persévérance et motivation. Ces sujets montrent que le collectif peut prendre soin de sa manière d’agir et de ses liens.

Après ton exercice, demande à un binôme de résumer le message en une phrase. S’il retient plusieurs idées sans lien, simplifie. Garde un exemple qui t’appartient et évite une confidence concernant quelqu’un d’autre. Tu peux ensuite choisir un défi dans les Archives pour prolonger la réflexion par une petite action.""",
"Mentors et passation : faire vivre l’héritage": """Un mentor accompagne le raisonnement et l’autonomie. Il peut poser une question, ouvrir une relation ou aider à comprendre une difficulté. Cet appui ne retire pas la responsabilité des étudiants : l’équipe doit préparer ses échanges et montrer ce qu’elle a essayé. Une demande précise permet un accompagnement plus utile.

Le professeur Ndiaga NDIAYE a marqué Enactus ESP par sa présence, sa générosité et son engagement auprès des générations. Continuer cet héritage peut prendre une forme quotidienne : accueillir une recrue, expliquer un choix et rester disponible pour une question. La transmission relie la mémoire des personnes et l’organisation du travail.

Pour relire ta fiche de passation, demande si une nouvelle personne sait ce qui est attendu et où commencer. Ajoute une décision expliquée, pas seulement une liste de documents. Prévois un échange où elle pourra reformuler et pratiquer. Honorer un accompagnement, c’est aussi rendre possible celui des personnes qui arrivent.""",
"Terrasen : une rencontre devient un diagnostic": """Une rencontre ouvre une relation et un accès au terrain, mais le diagnostic doit ensuite décrire les contraintes avec plusieurs interlocuteurs. Pour une activité agricole, regarde l’eau, le sol, la saison, le travail, la conservation et les débouchés. Une solution d’irrigation ne résout pas automatiquement une difficulté de vente.

Le micro-jardinage sur table et l’arrosage doivent être pensés comme des fonctions reliées. Qui fabrique les tables, qui règle le dispositif et qui intervient en cas de panne ? L’automatisation peut aider une tâche, tout en ajoutant des besoins d’énergie, de pièces et de compétence. La maintenance fait partie du choix technique.

Après ton exercice, place les responsables et les mesures sur la chaîne du projet. Une hausse de rendement envisagée doit rester un objectif tant qu’une comparaison n’existe pas. Ta carte est utile si elle permet de choisir une première question à vérifier. Terrasen aide ainsi à relier la technologie au fonctionnement d’une activité et au changement recherché.""",
"SHERY : concevoir avec les usages et les contraintes": """Une réponse à la précarité menstruelle doit être conçue avec les utilisatrices et leur laisser un choix. L’accès, les préférences, les conditions de lavage, le séchage et le coût influencent un usage réel. Les entretiens doivent rester respectueux : la personne peut ne pas répondre et n’a pas à partager une expérience intime pour participer.

La conception d’une protection et les informations qui l’accompagnent demandent des essais et des compétences appropriés. Une distinction récompense une initiative ; elle ne remplace pas une évaluation de sécurité, de qualité ou de confort. Le cours apprend à poser des questions de conception sans fournir de diagnostic ni de recommandation médicale individuelle.

Dans ton exercice, vérifie que chaque critère correspond à une question que la personne peut comprendre et refuser. « Quels aspects rendraient ce produit difficile à utiliser ? » peut ouvrir un échange sans exiger de détails personnels. La qualité de la réponse sociale dépend aussi de la liberté de choisir et de la prise en compte des contraintes quotidiennes.""",
"Transférer une technologie, transmettre une capacité": """Un transfert relie une démonstration à une pratique autonome et à un suivi. Décompose le procédé en gestes compréhensibles, explique leur raison, puis laisse les personnes essayer. Note ce qui demande encore une aide. La capacité acquise ne se mesure pas seulement au nombre de participants ou à la remise d’un équipement.

L’entretien et l’organisation doivent être transmis aussi. Les consommables, les pièces, les coûts et les règles d’accès influencent la continuité. Prévois une personne locale responsable et un échange après les premiers usages. Une difficulté signalée doit avoir un interlocuteur et une prochaine étape.

Après ton exercice, imagine que l’équipe étudiante devient indisponible. La personne locale sait-elle refaire le geste, entretenir le matériel et demander une aide adaptée ? Si une réponse manque, complète le transfert. Une technologie prend de la valeur lorsqu’elle devient une capacité utilisable dans le contexte des personnes, avec une organisation qui peut continuer à apprendre.""",
})
