import '../models/archive_models.dart';

class ArchivesService {
  Future<ArchivesHomeData> getArchives() async {
    await Future<void>.delayed(const Duration(milliseconds: 240));

    return const ArchivesHomeData(
      summary: ArchiveImpactSummaryModel(
        createdProjects: 5,
        developingProjects: 4,
        developedProducts: 14,
        touchedSdgs: 11,
        createdJobs: 227,
        savedLives: 206,
        plantedTrees: 1425,
        cumulativeUsdGains: 46236.7,
        cumulativeFcfaGains: 27468761,
        impactedLives: 15900,
      ),
      projects: [
        ArchiveProjectModel(
          id: 'dimbali',
          name: 'DIMBALI',
          summary:
              'Projet historique autour de la nutrition, du reboisement et de la création de revenus locaux.',
          launchYear: 2016,
          archiveYear: 2020,
          locality: 'Sénégal',
          target: 'Communautés vulnérables, femmes et jeunes',
          problem:
              'Malnutrition, faibles revenus locaux et pression environnementale.',
          solution:
              'Valorisation de ressources locales, activités génératrices de revenus et actions environnementales.',
          actions: [
            'Structuration communautaire',
            'Développement de produits',
            'Sensibilisation nutritionnelle',
            'Reboisement',
          ],
          sdgs: ['ODD 2', 'ODD 8', 'ODD 13'],
          products: ['Produits nutritionnels', 'Produits locaux transformés'],
          revenue: 8600000,
          profit: 2100000,
          jobs: 54,
          impactedLives: 4200,
          savedLives: 72,
          plantedTrees: 620,
          partners: ['Communautés locales', 'Partenaires techniques'],
          awards: ['Champion National 2017', 'Champion National 2018'],
          documents: ['Présentation Enactus ESP 2020', 'Rapports impact'],
          members: ['Équipe projet Dimbali', 'Alumni Enactus ESP'],
          lessons: [
            'Mesurer tôt les preuves terrain',
            'Former les relais locaux',
            'Relier impact social et viabilité économique',
          ],
          status: 'archivé',
          expansionReady: true,
        ),
        ArchiveProjectModel(
          id: 'deconaane',
          name: 'DECONAANE',
          summary:
              'Projet lié à l’eau sûre, au moringa, à la prévention sanitaire et aux revenus.',
          launchYear: 2016,
          archiveYear: 2020,
          locality: 'Sénégal',
          target: 'Familles et communautés exposées aux risques sanitaires',
          problem: 'Accès insuffisant à une eau sûre et prévention limitée.',
          solution:
              'Approche communautaire combinant traitement, sensibilisation et valorisation du moringa.',
          actions: [
            'Sensibilisation santé',
            'Production locale',
            'Distribution encadrée',
          ],
          sdgs: ['ODD 3', 'ODD 6', 'ODD 8'],
          products: ['Solutions santé', 'Produits à base de moringa'],
          revenue: 5200000,
          profit: 1200000,
          jobs: 38,
          impactedLives: 3100,
          savedLives: 58,
          plantedTrees: 210,
          partners: ['Relais communautaires', 'Acteurs santé'],
          awards: ['4 prix sur 5 à la compétition Uhodari 2016'],
          documents: ['Présentation Enactus ESP 2020'],
          members: ['Équipe projet Deconaane'],
          lessons: [
            'La confiance locale est centrale',
            'Un bon produit doit être accompagné d’éducation',
          ],
          status: 'expansion',
          expansionReady: true,
        ),
        ArchiveProjectModel(
          id: 'javelisel',
          name: 'JAVELISEL',
          summary:
              'Projet de santé publique autour de l’eau de javel et de la prévention des maladies.',
          launchYear: 2015,
          archiveYear: 2019,
          locality: 'Sénégal',
          target: 'Ménages et structures communautaires',
          problem: 'Prévention insuffisante de maladies liées à l’hygiène.',
          solution:
              'Production et diffusion de solutions de désinfection accessibles avec sensibilisation.',
          actions: ['Production', 'Sensibilisation', 'Démonstrations terrain'],
          sdgs: ['ODD 3', 'ODD 6'],
          products: ['Eau de javel', 'Kits de sensibilisation'],
          revenue: 3100000,
          profit: 780000,
          jobs: 22,
          impactedLives: 2100,
          savedLives: 46,
          plantedTrees: 0,
          partners: ['Communautés locales'],
          awards: ['Premier Prix d’Excellence Fondation Sonatel'],
          documents: ['Présentation Enactus ESP 2020'],
          members: ['Équipe Javelisel'],
          lessons: [
            'La pédagogie d’usage compte autant que le produit',
            'Le packaging doit rester simple et sûr',
          ],
          status: 'archivé',
          expansionReady: false,
        ),
        ArchiveProjectModel(
          id: 'mobigel',
          name: 'MOBIGEL',
          summary:
              'Innovation rapide née en contexte Covid-19 autour de l’hygiène mobile.',
          launchYear: 2020,
          archiveYear: 2021,
          locality: 'Campus et espaces publics',
          target: 'Usagers exposés aux risques sanitaires',
          problem:
              'Besoin urgent de solutions d’hygiène accessibles et mobiles pendant la crise sanitaire.',
          solution:
              'Dispositif mobile facilitant l’accès au gel ou à l’hygiène préventive.',
          actions: [
            'Prototype rapide',
            'Tests utilisateurs',
            'Sensibilisation',
          ],
          sdgs: ['ODD 3', 'ODD 9'],
          products: ['Dispositif Mobigel'],
          revenue: 950000,
          profit: 230000,
          jobs: 8,
          impactedLives: 1200,
          savedLives: 30,
          plantedTrees: 0,
          partners: ['ESP', 'Communauté campus'],
          awards: ['Parution presse', 'Passage TV'],
          documents: ['Présentation Enactus ESP 2020'],
          members: ['Équipe Mobigel'],
          lessons: [
            'La vitesse d’exécution peut sauver la pertinence',
            'Tester vite réduit les mauvaises hypothèses',
          ],
          status: 'terminé',
          expansionReady: true,
        ),
        ArchiveProjectModel(
          id: 'meune-nagn',
          name: 'MEUNE NAGN',
          summary:
              'Projet autour de la chaîne de valeur, de la coopérative et des ressources de Casamance.',
          launchYear: 2018,
          archiveYear: 2020,
          locality: 'Casamance',
          target: 'Producteurs, coopératives et jeunes',
          problem:
              'Chaînes de valeur locales peu structurées et revenus instables.',
          solution:
              'Organisation coopérative, transformation et meilleure commercialisation.',
          actions: ['Diagnostic terrain', 'Structuration', 'Transformation'],
          sdgs: ['ODD 1', 'ODD 8', 'ODD 12'],
          products: ['Produits locaux transformés'],
          revenue: 6400000,
          profit: 1600000,
          jobs: 61,
          impactedLives: 2800,
          savedLives: 0,
          plantedTrees: 320,
          partners: ['Coopératives locales'],
          awards: ['Intervention RFI'],
          documents: ['Présentation Enactus ESP 2020'],
          members: ['Équipe Meune Nagn'],
          lessons: [
            'La gouvernance locale doit être claire',
            'La valeur ajoutée se construit dans la chaîne complète',
          ],
          status: 'archivé',
          expansionReady: true,
        ),
        ArchiveProjectModel(
          id: 'soukhali',
          name: 'SOUKHALI',
          summary:
              'Valorisation de ressources locales comme le Neem, la mangue et le Madd.',
          launchYear: 2017,
          archiveYear: 2020,
          locality: 'Sénégal',
          target: 'Producteurs et consommateurs locaux',
          problem: 'Ressources locales sous-valorisées et pertes post-récolte.',
          solution:
              'Transformation, branding et création de débouchés commerciaux.',
          actions: ['Recherche produit', 'Transformation', 'Vente pilote'],
          sdgs: ['ODD 8', 'ODD 12'],
          products: ['Neem', 'Mangue transformée', 'Madd transformé'],
          revenue: 4200000,
          profit: 930000,
          jobs: 32,
          impactedLives: 1900,
          savedLives: 0,
          plantedTrees: 185,
          partners: ['Producteurs locaux'],
          awards: ['Deuxième National Compétition Nationale 2016'],
          documents: ['Présentation Enactus ESP 2020'],
          members: ['Équipe Soukhali'],
          lessons: [
            'Le design produit aide la confiance',
            'Les pertes post-récolte sont une opportunité d’impact',
          ],
          status: 'archivé',
          expansionReady: true,
        ),
        ArchiveProjectModel(
          id: 'kong-serve',
          name: 'KONG’SERVE',
          summary:
              'Projet de conservation et transformation pour réduire les pertes et créer de la valeur.',
          launchYear: 2018,
          archiveYear: 2020,
          locality: 'Sénégal',
          target: 'Producteurs et ménages',
          problem:
              'Pertes alimentaires et faible durée de conservation des produits.',
          solution:
              'Méthodes de conservation et produits transformés adaptés au marché local.',
          actions: ['Tests de conservation', 'Prototypage', 'Vente pilote'],
          sdgs: ['ODD 2', 'ODD 12'],
          products: ['Produits conservés', 'Solutions de transformation'],
          revenue: 2500000,
          profit: 540000,
          jobs: 12,
          impactedLives: 900,
          savedLives: 0,
          plantedTrees: 40,
          partners: ['Producteurs locaux'],
          awards: [],
          documents: ['Présentation Enactus ESP 2020'],
          members: ['Équipe Kong’Serve'],
          lessons: [
            'La conservation doit rester accessible',
            'Le marché valide mieux que l’idée seule',
          ],
          status: 'développement',
          expansionReady: false,
        ),
        ArchiveProjectModel(
          id: 'sukhalii-gokh',
          name: 'SUKHALII GOKH',
          summary:
              'Projet d’amélioration locale centré sur le quartier et la participation communautaire.',
          launchYear: 2019,
          archiveYear: 2020,
          locality: 'Quartiers partenaires',
          target: 'Habitants et jeunes locaux',
          problem:
              'Besoins locaux dispersés et manque de coordination communautaire.',
          solution:
              'Actions de quartier, mobilisation et micro-initiatives structurées.',
          actions: ['Diagnostic participatif', 'Actions locales', 'Suivi'],
          sdgs: ['ODD 11', 'ODD 17'],
          products: ['Actions communautaires'],
          revenue: 520000,
          profit: 90000,
          jobs: 0,
          impactedLives: 700,
          savedLives: 0,
          plantedTrees: 50,
          partners: ['Communautés locales'],
          awards: [],
          documents: ['Présentation Enactus ESP 2020'],
          members: ['Équipe Sukhalii Gokh'],
          lessons: [
            'La participation locale améliore la durabilité',
            'Les petits actes doivent être documentés',
          ],
          status: 'archivé',
          expansionReady: true,
        ),
      ],
      hallOfFame: [
        HallOfFameItemModel(
          title: 'Premier Prix d’Excellence Fondation Sonatel',
          period: 'Historique',
          description: 'Reconnaissance de l’excellence et de l’impact terrain.',
          type: 'Prix',
        ),
        HallOfFameItemModel(
          title: 'Deuxième National Compétition Nationale',
          period: '2016',
          description: 'Performance nationale majeure pour Enactus ESP.',
          type: 'Compétition',
        ),
        HallOfFameItemModel(
          title: '4 prix sur 5 à la compétition Uhodari',
          period: '2016',
          description: 'Palmarès remarquable sur plusieurs catégories.',
          type: 'Compétition',
        ),
        HallOfFameItemModel(
          title: 'Champion National',
          period: '2017',
          description: 'Qualification au plus haut niveau national.',
          type: 'Titre',
        ),
        HallOfFameItemModel(
          title: 'Champion National',
          period: '2018',
          description: 'Confirmation de la dynamique d’excellence.',
          type: 'Titre',
        ),
        HallOfFameItemModel(
          title: 'Demi-finaliste compétition internationale',
          period: '2018',
          description: 'Rayonnement international des projets Enactus ESP.',
          type: 'International',
        ),
        HallOfFameItemModel(
          title: 'Parution presse, passage TV et intervention RFI',
          period: 'Historique',
          description: 'Visibilité médiatique et crédibilité publique du club.',
          type: 'Média',
        ),
      ],
    );
  }
}
