import '../models/impact_models.dart';

class ImpactService {
  Future<ImpactDashboardData> getDashboard() async {
    await Future<void>.delayed(const Duration(milliseconds: 260));

    const projects = [
      ProjectImpactMetricModel(
        id: 'p1',
        projectName: 'Green Campus ESP',
        status: 'Actif',
        poleName: 'Environnement',
        projectLead: 'Awa Diagne',
        deputyLead: 'Mamadou Fall',
        sdgs: ['ODD 11', 'ODD 12', 'ODD 13'],
        problem: 'Gestion insuffisante des déchets et faible tri à la source.',
        solution:
            'Collecte intelligente, sensibilisation et valorisation locale.',
        targetBeneficiaries: 'Étudiants, personnel ESP et riverains',
        directImpact: 184,
        indirectImpact: 920,
        reach: 3200,
        revenue: 480000,
        surplus: 122000,
        planetImpact: 76,
        evidenceCount: 7,
        methodology: 'Pesées hebdomadaires, enquêtes et photos géolocalisées.',
        assumptions:
            'Projection basée sur 18 semaines de collecte et trois sites pilotes.',
        budgetUsed: 310000,
        progress: 72,
        completedTasks: 34,
        lateTasks: 4,
        documentsCount: 12,
        innovationScore: 82,
        businessViabilityScore: 68,
        scalabilityScore: 74,
        competitionReadinessScore: 70,
      ),
      ProjectImpactMetricModel(
        id: 'p2',
        projectName: 'Sama Skills',
        status: 'Prototype',
        poleName: 'Éducation',
        projectLead: 'Cheikh Ndiaye',
        deputyLead: 'Fatou Sarr',
        sdgs: ['ODD 4', 'ODD 8'],
        problem:
            'Manque de repères pratiques pour l’insertion des jeunes apprenants.',
        solution:
            'Parcours courts, ateliers soft skills et mentorat alumni ciblé.',
        targetBeneficiaries: 'Étudiants de première et deuxième année',
        directImpact: 96,
        indirectImpact: 410,
        reach: 1450,
        revenue: 210000,
        surplus: 46000,
        planetImpact: 28,
        evidenceCount: 3,
        methodology: 'Feuilles de présence, quiz avant/après et entretiens.',
        assumptions:
            'Impact indirect estimé par diffusion des ressources aux promotions.',
        budgetUsed: 180000,
        progress: 48,
        completedTasks: 21,
        lateTasks: 7,
        documentsCount: 6,
        innovationScore: 69,
        businessViabilityScore: 57,
        scalabilityScore: 71,
        competitionReadinessScore: 52,
      ),
      ProjectImpactMetricModel(
        id: 'p3',
        projectName: 'Market Link',
        status: 'Exploration',
        poleName: 'Entrepreneuriat',
        projectLead: 'Mouhamed Ba',
        deputyLead: 'Ndeye Gueye',
        sdgs: [],
        problem:
            'Petits vendeurs peu visibles et difficulté à suivre les ventes.',
        solution:
            'Mini vitrine numérique, suivi simple des revenus et relais campus.',
        targetBeneficiaries: 'Micro-vendeurs et associations étudiantes',
        directImpact: 42,
        indirectImpact: 180,
        reach: 740,
        revenue: 95000,
        surplus: 14000,
        planetImpact: 18,
        evidenceCount: 1,
        methodology: 'Entretiens exploratoires et registre de ventes pilote.',
        assumptions:
            'Les projections financières restent à confirmer avec plus de données.',
        budgetUsed: 88000,
        progress: 31,
        completedTasks: 12,
        lateTasks: 6,
        documentsCount: 3,
        innovationScore: 73,
        businessViabilityScore: 62,
        scalabilityScore: 66,
        competitionReadinessScore: 34,
      ),
    ];

    const poles = [
      PolePerformanceModel(
        poleName: 'Veille & Recrutement',
        activeMembers: 9,
        attendanceRate: 84,
        completedTasks: 38,
        lateTasks: 5,
        documentsCount: 11,
        postsCount: 9,
        linkedProjects: 2,
        academyProgress: 62,
        alerts: 1,
      ),
      PolePerformanceModel(
        poleName: 'Projets',
        activeMembers: 14,
        attendanceRate: 78,
        completedTasks: 61,
        lateTasks: 12,
        documentsCount: 18,
        postsCount: 13,
        linkedProjects: 5,
        academyProgress: 56,
        alerts: 2,
      ),
      PolePerformanceModel(
        poleName: 'Communication',
        activeMembers: 8,
        attendanceRate: 88,
        completedTasks: 44,
        lateTasks: 3,
        documentsCount: 14,
        postsCount: 27,
        linkedProjects: 3,
        academyProgress: 69,
        alerts: 0,
      ),
    ];

    const enacteurs = [
      EnacteurPerformanceModel(
        memberName: 'Awa Diagne',
        attendanceRate: 92,
        punctualityRate: 86,
        completedTasks: 18,
        validatedTasks: 15,
        projectContributions: 10,
        eventsParticipation: 5,
        producedDocuments: 7,
        usefulPosts: 6,
        academyLessonsCompleted: 9,
        passedQuizzes: 5,
        badges: 4,
        leadershipScore: 82,
        collaborationScore: 88,
      ),
      EnacteurPerformanceModel(
        memberName: 'Cheikh Ndiaye',
        attendanceRate: 81,
        punctualityRate: 79,
        completedTasks: 15,
        validatedTasks: 11,
        projectContributions: 8,
        eventsParticipation: 4,
        producedDocuments: 4,
        usefulPosts: 5,
        academyLessonsCompleted: 7,
        passedQuizzes: 4,
        badges: 3,
        leadershipScore: 74,
        collaborationScore: 80,
      ),
      EnacteurPerformanceModel(
        memberName: 'Fatou Sarr',
        attendanceRate: 88,
        punctualityRate: 84,
        completedTasks: 14,
        validatedTasks: 13,
        projectContributions: 7,
        eventsParticipation: 6,
        producedDocuments: 6,
        usefulPosts: 7,
        academyLessonsCompleted: 8,
        passedQuizzes: 6,
        badges: 4,
        leadershipScore: 79,
        collaborationScore: 91,
      ),
    ];

    return ImpactDashboardData(
      organization: OrganizationPerformanceModel(
        activeMembers: 46,
        attendanceRate: 82,
        retentionRate: 76,
        completedTasks: 176,
        lateTasks: 24,
        activeProjects: projects.length,
        directImpactTotal: projects.fold(
          0,
          (sum, item) => sum + item.directImpact,
        ),
        indirectImpactTotal: projects.fold(
          0,
          (sum, item) => sum + item.indirectImpact,
        ),
        reachTotal: projects.fold(0, (sum, item) => sum + item.reach),
        revenueTotal: projects.fold(0, (sum, item) => sum + item.revenue),
        surplusTotal: projects.fold(0, (sum, item) => sum + item.surplus),
        officialDocuments: projects.fold(
          0,
          (sum, item) => sum + item.documentsCount,
        ),
        competitionReadiness:
            projects.fold(
              0.0,
              (sum, item) => sum + item.competitionReadinessScore,
            ) /
            projects.length,
        academyParticipation: 61,
        communicationEngagement: 74,
        financialHealth: 69,
      ),
      projects: projects,
      enacteurs: enacteurs,
      poles: poles,
    );
  }
}
